apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: load-balancer-nginx
  name: hello-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer-nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-balancer-nginx
    spec:
      containers:
      - image: nginx
        name: hello-nginx
        ports:
        - containerPort: 80