apiVersion: v1
kind: Service
metadata:
  name: svc-node-redis
  labels:
    name: svc-node-redis
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    name: node-redis
