from sqlalchemy import Column, Integer, String, Boolean, DateTime, Text, func
from .database import Base

class Todo(Base):
    """
    SQLAlchemy model for the 'todos' table.
    Matches the requirements defined in the PRD and API Spec.
    """
    __tablename__ = "todos"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    is_completed = Column(Boolean, default=False)
    
    # Audit fields
    created_by = Column(String, nullable=False)
    
    # func.now() ensures the timestamp is generated by the DB server
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    # onupdate=func.now() updates this field whenever the row is modified
    updated_at = Column(
        DateTime(timezone=True), 
        server_default=func.now(), 
        onupdate=func.now()
    )