import type { NextPage } from 'next';
import Head from 'next/head';
import { useRef, useState } from 'react';

const Home: NextPage = () => {
  const [isVideoPlaying, setIsVideoPlaying] = useState(false);
  const [stream, setStream] = useState<MediaStream | null>(null);
  const videoElement = useRef<HTMLVideoElement>(null);
  const toggleVideo = () => {
    const constraints = { video: true, audio: true };

    setIsVideoPlaying(!isVideoPlaying);
    if (!isVideoPlaying) {
      navigator.mediaDevices.getUserMedia(constraints).then((curStream) => {
        setStream(curStream);
        if (videoElement.current) {
          videoElement.current.srcObject = curStream;
        }
      });
    } else {
      if (videoElement.current) {
        stream?.getTracks().forEach((track) => track.stop());
        videoElement.current.srcObject = null;
      }
    }
  };
  return (
    <div>
      <Head>
        <title>Nextjs WebRTC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Nextjs WebRTC</h1>
        <div>
          <button onClick={toggleVideo}>Start Video</button>
        </div>
        <div>
          <video ref={videoElement} autoPlay playsInline />
        </div>
      </main>
    </div>
  );
};

export default Home;
